// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_TextArea1;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui____initial_actions0;

// SCREEN: ui_Screen3（摄像头预览 — 自定义添加）
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_BtnCapture(lv_event_t * e);
void ui_event_BtnRecord(lv_event_t * e);
void ui_event_BtnBack(lv_event_t * e);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
