// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>


//获取百度语音识别模型数据 
int get_baidu_asr_model_data(char *text)
{
    int ret;
    FILE *fp;
    char buffer[4096];
    size_t n;


    printf("正在采集音频...\n");
    system("arecord -d 5 -f S16_LE -r 16000 -c 1 output.wav ");

    printf("音频采集完成\n");

    printf("正在发送请求到百度语音识别API...\n");
    fp = popen(
        "curl -s -i -X POST "
        "-H \"Content-Type: audio/wav;rate=16000\" "
        "\"http://vop.baidu.com/pro_api?dev_pid=80001&cuid=gec6818&token=24.4c5ea35cb66fc78ce1dcbd4d51ef3bdc.2592000.1784014367.282335-123704183\" "
        "--data-binary \"@output.wav\"",
        "r"
    );
    if (fp == NULL) {
        printf("popen失败\n");
        return 1;
    }

    while ((n = fread(buffer, 1, sizeof(buffer)-1, fp)) > 0) {
        buffer[n] = '\0';
       // printf("%s", buffer);

        //查找结果  result  
        char *p = strstr(buffer,"result"); 
        if(p != NULL)
        {
           //result":["你在干什么事？"] 
            p = p + 10;  //p指向 -> 你  

           // printf("%s", p);  

            //p->  你是谁？"],"sn":"458085303111781427197"} 
            
             char *q = strstr(p,"\"");  //q -> 指向  " 
             *q = '\0'; //添加结束符号
            // printf("%s", p); 

             strcpy(text,p); //拷贝数据
        }


    }
    printf("\n=== 响应结束 ===\n");

    pclose(fp);
    return 0;
}


//语音识别按钮点击事件
void get_asr_text(lv_event_t * e)
{
	// Your code here
	char text[1024] = {0};
	get_baidu_asr_model_data(text);
	printf("text: %s\n",text);

	//设置到标签中
	lv_label_set_text(ui_Label1,text);
}

//输入法按钮点击事件
void get_input_set_label(lv_event_t * e)
{
	// Your code here
	//获取输入框的文本信息 
   char *text = lv_textarea_get_text(ui_TextArea1);
   printf("text: %s\n",text);

   //设置到标签中
   lv_label_set_text(ui_Label1,text);
}
